---
- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: Remove VLANs
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}} 
        username={{eapi_username}}
        password={{eapi_password}}
        host={{eapi_hostname}}
        port={{eapi_port}}
        transport=https
      with_items:
         - {name: VLAN100, vlanid: 100}
         - {name: VLAN200, vlanid: 200}
         - {name: VLAN300, vlanid: 300}
