---
- name: Create Arista VLANs
  hosts: arista

  tasks:

   - name: Set Ethernet7 description
     eos_interface: name=Ethernet7  description="IN USE"
        username={{eapi_username}} 
        password={{eapi_password}}
        host={{eapi_hostname}}
        port={{eapi_port}}
        transport=https


   - name: Set Ethernet7 to access mode, VLAN1
     eos_switchport: name=Ethernet7 mode=access access_vlan=100 
        username={{eapi_username}}
        password={{eapi_password}}
        host={{eapi_hostname}}
        port={{eapi_port}}
        transport=https
                         
