
- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: Set Ethernet7 description
      eos_interface: name=Ethernet7  description="IN USE"
        username={{eapi_username}}
        password={{eapi_password}}
        host={{eapi_hostname}}
        port={{eapi_port}}
        transport=https

