---
- name: Create Arista VLANs
  hosts: arista

  tasks:

    - name: Restore Primary Interface Descrition
      eos_interface: name=Ethernet7  description=""
        username={{eapi_username}} 
        password={{eapi_password}}
        host={{eapi_hostname}}
        port={{eapi_port}}
        transport=https
                         

    - name: Primary Interface 
      eos_switchport: name=Ethernet7 mode=access access_vlan=1 trunk_allowed_vlans=1-4094 
        username={{eapi_username}}
        password={{eapi_password}}
        host={{eapi_hostname}}
        port={{eapi_port}}
        transport=https



    - name: Remove VLANs
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}} state=absent
        username={{eapi_username}}
        password={{eapi_password}}
        host={{eapi_hostname}}
        port={{eapi_port}}
        transport=https
      with_items:
         - {name: VLAN100, vlanid: 100}
         - {name: VLAN200, vlanid: 200}
         - {name: VLAN300, vlanid: 300}
                        
