---
- name: Create Arista VLANs
  hosts: arista

  tasks:

    - name: Set Ethernet7 to access mode, VLAN1
      eos_switchport: name=Ethernet7 mode=access access_vlan=1 trunk_allowed_vlans=1-4094 trunk_native_vlan=1
        username={{eapi_username}}
        password={{eapi_password}}
        host={{eapi_hostname}}
        port={{eapi_port}}
        transport=https
